# Default server configuration.
host: 127.0.0.1
port: 3000
postgres:
  host: localhost
  port: 5432
  database_name: appdb
  username: postgres
  password: Fiona2021
  useSSL: false
  time_zone: UTC
jwt_secret: "WXY7lj1CWCpuEih8OYLPne2manlnbAfg"
